[WIP] Adapt Data Track
wakutech/react-native-twilio-video-webrtc pull request #1
Opened 2018-08-08 09:01 UTC by ykkc

## :thought_balloon: 背景
(問題の背景を記述)

- LessonRoomから取得するDataTrackMessageを取得できるようにしたい。

## :memo: 概要
(変更内容を記述)

- TwilioのライブラリのDataTrack用のインターフェースの実装をした。

## :ticket: 関連リンク
(関連するリンクがあれば箇条書きで記述)

https://qiita.com/shinout/items/c6f12d69e68b312d62fa

## :heavy_check_mark: 動作確認
(レビュアーに確認してもらいたい項目を箇条書きで記述)

**レビュアーは動作確認項目にチェックを入れてください**
- [ ] 机上レビューで大丈夫だと思います。(動作確認済)

## レビューを依頼する前の確認事項
**レビューに出す前にチェックを入れよう**

- [x] 変更内容に過不足がない
- [x] 動作確認項目について自分でもチェックをした

2018-08-08 19:30 UTC, ykkc commented on android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java
> +            public void onMessage(String message) {
Android、誰が送ったmessageかわからん(sidがない)のかーい

2018-08-10 01:55 UTC, ykkc commented on android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java
> +            public void onMessage(String message) {
そんなことなかった。公式のドキュメントが間違ってた

2018-08-10 14:18 UTC, p-oka commented
fitra_react_native側で動作確認ができていないのでPEND

2018-08-10 14:39 UTC, p-oka requested changes
確認したか自分が分かるように、Request changesステータスにしておきますm(_ _)m

2018-08-21 07:00 UTC, p-oka approved these changes

2018-08-22 17:51 UTC, merged